services:
  api:
    build:  
      context: ./api
      dockerfile: Dockerfile
    container_name: loja_api
    command: node dist/main.js
    ports:
      - "8080:3000"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    networks:  
      - loja-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - loja-network


  db:
    image:   postgres:16
    container_name: loja_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loja_db
    ports:  
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - loja-network
    healthcheck:
      test:   ["CMD-SHELL", "pg_isready -U postgres -d loja_db"]
      interval: 5s
      retries: 5
      timeout:   5s
      start_period: 10s

  redis:  
    image: redis:7
    container_name: loja_redis
    ports:
      - "6379:6379"
    networks:
      - loja-network

networks:
  loja-network: 
    driver:   bridge

volumes:
  pgdata:



