

services:
  api-dev:
    image: node:18-alpine
    container_name: loja_api_dev
    working_dir: /app
    command: npm run start:dev
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loja-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loja_frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://api:3000
    depends_on:
      - api
    networks:
      - loja-network

  db:
    image: postgres:16
    container_name: loja_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loja-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 10s

  redis:
    image: redis:7
    container_name: loja_redis
    ports:
      - "6379:6379"
    networks:
      - loja-network


networks:
  loja-network:
    driver: bridge

volumes:
  pgdata:




