version: '3.9'

services:
  api:
    build:
      context: ./api      
      dockerfile: Dockerfile
    container_name: loja_api
    command: npm run start:dev
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - loja-network

  db:
    image: postgres:16
    container_name: loja_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loja-network

  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - loja-network

  zookeeper:
    image: bitnami/zookeeper:3
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - loja-network


networks:
  loja-network:
    driver: bridge

volumes:
  pgdata:

