name: Deploy to EC2

on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # ← IMPORTANTE: usa o runner no EC2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old containers
        run: |
          docker stop frontend backend 2>/dev/null || true
          docker rm frontend backend 2>/dev/null || true

      - name: Build frontend
        run: |
          docker build -t frontend:latest -f frontend/Dockerfile frontend

      - name: Build backend
        run: |
          docker build -t backend:latest -f api/Dockerfile api

      - name: Run frontend
        run: |
          docker run -d --name frontend --restart unless-stopped -p 80:80 frontend:latest

      - name: Run backend
        run: |
          docker run -d --name backend --restart unless-stopped -p 3000:3000 backend:latest

      - name:  Cleanup
        run: |
          docker image prune -f

      - name: Show status
        run: |
          docker ps
